### ISSUE TITLE
Banner disappears whenever the page is saved again

### ISSUE THREAD

**Issue by ronnieduke** [stevewithington/MuraBanners#1]
Steps to reproduce:
1. Upload a banner to a page & publish
2. Go back and edit the page again and publish
3. Banner disappears.

**Comment by ronnieduke** [comment]
Here is a video of the error in action: http://screencast.com/t/eO2qCickHJqq

Also, I am on Mura 5.6.4971 / CF 9.0.1

**Comment by stevewithington** [comment]
I just confirmed the issue myself.  I'll let you know when I get a chance to fix it.  Thanks!

**Comment by stevewithington** [comment]
This appears to be an issue with Mura and Extended Attributes. I've created an issue there instead:
https://github.com/blueriver/MuraCMS/issues/452

**Comment by ronnieduke** [comment]
Oh okay… thanks Steve!

Does this affect all extended attributes? Or just in relation to this plugin?

**Comment by stevewithington** [comment]
It's not the plugin...it's any extended attribute with a "File" form field type.
